language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-start-site' ]; then cd .. && eval "mv $currentfolder generator-start-site" && cd generator-start-site; fi

